### ISSUE TITLE
investigate Travis QA on Node JS

### ISSUE THREAD

**Issue by Keuchsieu** [TeamProject07/ProjectResume#18]
what should we put into script section to test get and request functions?

**Comment by Keuchsieu** [comment]
Travis CI can do JavaScript unit test along with Jasmine and KarmaJS. Should we spend more time on implement Jasmine and KarmaJS?

>-KarmaJS:
https://karma-runner.github.io/2.0/index.html
-Jasmine
>https://jasmine.github.io

**Comment by PashanIrani** [comment]
If you feel it's needed feel free too. But most of the methods and stuff will be most likely written within the `vue` files.

**Comment by Keuchsieu** [comment]
Isn't vue for front end?

**Comment by PashanIrani** [comment]
right, I assumed we'd write unit tests for ALL methods, but if this is solely for backend, I think we should implement it. **If** it doesn't add too much time to the development.
