### ISSUE TITLE
" 'X' found under Y " display sentence always lowers the search queries capitals. Slightly inconsistent.

### ISSUE THREAD

**Issue by Justin-Carey** [TeamProject07/ProjectResume#224]
For example. If "Java" was searched, it will save "java" found under Skills

**Comment by Justin-Carey** [comment]
Also, it doesn't always show for each record. I think it has to do with clicking a skill inside of an record. 
![image](https://user-images.githubusercontent.com/21072673/39686193-761e5c8e-517c-11e8-9fbc-2b090e036cfc.png)

**Comment by PashanIrani** [comment]
fixed
