### ISSUE TITLE
Implement Travis CI

### ISSUE THREAD

**Issue by PashanIrani** [TeamProject07/ProjectResume#6]

**Comment by Keuchsieu** [comment]
What is our end state for the server? If we don't have one, the build in Travis can never succeed, it runs until hit time uplimit exception

**Comment by PashanIrani** [comment]
@Keuchsieu is this still an issue? if so we shall discuss this in our meeting tmr.

Cheers!

**Comment by Keuchsieu** [comment]
Nope after the implementation of webpack
