### ISSUE TITLE
Use 'npm run prod' in travis CI

### ISSUE THREAD

**Issue by PashanIrani** [TeamProject07/ProjectResume#9]
After the setup has been committed, you should test the prod build on travis CI, it doesn't watch for file changes.

**Comment by Keuchsieu** [comment]
Actually, I think it does, i received the build pass message when I was doing DataCom

**Comment by PashanIrani** [comment]
ah, but in my recent commits (in master), the build command has been changed.

Prod Build: 
`npm run prod`

Dev (Idk this needs to be tested)
`npm start`

### Why I think dev shouldn't be tested?
Only difference right now is that dev is constantly watching for changes and builds the code. In the future Prod configs, we will have Uglification features, but syntactically and error-wise there really won't be much of difference between **prod** and **dev**.

**Comment by PashanIrani** [comment]
this has been fixed.
